#Copyright 2019 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
language: python

before_install:
  - wget -O install.sh "https://github.com/bazelbuild/bazel/releases/download/0.26.1/bazel-0.26.1-installer-linux-x86_64.sh"
  - chmod +x install.sh
  - ./install.sh --user
  - rm -f install.sh
  - sudo apt-get -y install libopenexr-dev
  - sudo apt-get -y install libgles2-mesa-dev
  - sudo apt-get -y install libc-ares-dev
  - sudo apt-get -y install pylint
  - pip install -U python-coveralls
  - pip install -U flake8
  - pip install -r requirements.txt

jobs:
  include:
    - os: linux
      python: 2.7
      install:
        - pip install -U tensorflow
    - os: linux
      python: 3.6
      install:
        - pip install -U tensorflow
    - os: linux
      python: 3.6
      install:
        - pip install -U tf-nightly

script:
  # - /usr/bin/pylint --rcfile=.pylintrc ./tensorflow_graphics/
  - flake8 --config=.flake8 ./tensorflow_graphics/
  - bazel test //tensorflow_graphics/...

after_success:
  - coveralls

notifications:
  email:
    recipients:
      - tf-graphics-eng@google.com
    on_success: never
    on_failure: always
