language: python

# see: https://docs.travis-ci.com/user/job-lifecycle/
language: python

jobs:
  include:
    - name: TensorFlow Release
      os: linux
      python: 3.6
      before_install:
        - pip install -U tensorflow
    # - name: TensorFlow Nightly
    #   os: linux
    #   python: 3.6
    #   before_install:
    #     - pip install -U tf-nightly

before_script:
  - wget -O install.sh "https://github.com/bazelbuild/bazel/releases/download/0.26.1/bazel-0.26.1-installer-linux-x86_64.sh"
  - chmod +x install.sh
  - ./install.sh --user
  - rm -f install.sh
  - sudo apt-get -y install libopenexr-dev
  - sudo apt-get -y install libgles2-mesa-dev
  - sudo apt-get -y install libc-ares-dev
  - sudo apt-get -y install pylint
  - pip install -U python-coveralls
  - pip install -U flake8
  - pip install -r requirements.txt

script:
  # --- run linter
  - flake8 --config=.flake8 ./tensorflow_graphics/
  # /usr/bin/pylint --rcfile=.pylintrc ./tensorflow_graphics/
  # --- test the codebase
  - export PYTHONPATH=$PWD:$PYTHONPATH
  - pytest tensorflow_graphics
  # --- build pip package (installs in python path)
  - python setup.py sdist bdist_wheel
  - pip install dist/tensorflow_graphics*.whl
  # --- test the pip package
  - cd $(mktemp -d) && python -c 'import tensorflow_graphics as tfg'

after_success:
  - coveralls

notifications:
  email:
    recipients:
      - tf-graphics-eng@google.com
    on_success: never
    on_failure: always
